@startuml
class クエスト {
  内容
  期限
  報酬額
  タグ
  ステータス
  依頼人
}

class 依頼人 {
  アドレス
  発行クエスト一覧
}

class 請負人 {
  アドレス
}

class パーティ {
  請負人
}

class ギルド {
  クエスト一覧
}

クエスト -o ギルド
クエスト -- パーティ
クエスト -- 請負人
請負人 -* パーティ
クエスト -o 依頼人
@enduml